services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/bot:Z
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - bot_network
    command: ["/bin/bash", "-c", "/app/wait-for-db.sh alembic upgrade head && python -m bot.bot"]

  db:
    image: postgres:17.2
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - bot_network
  
  redis:
    image: redis:7.4
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - bot_network

volumes:
  postgres_data:

networks:
  bot_network: